name: Build Now

on: 
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-24.04

   
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Start
      run: |
        ./build

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.TOKEN_GITHUB }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Flashable zip"
        files: |
         /home/runner/work/ANY/*.zip
