name: Build Now

on: 
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-24.04

   
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Start
      run: |
        ./build

    - name: Generate release tag
      id: generate_release_tag
      uses: amitsingh-007/next-release-tag@main
      with:
        repo_token: ${{ secrets.TOKEN_GITHUB }}
        automatic_release_tag: latest
        prerelease: true
        title: Flashable zip
        files: |
         /home/runner/work/ANY/*.zip
