name: Fast_Builder

on: 
  workflow_dispatch:
    inputs:
      DEVICE_NAME:
        description: 'Build'
        required: true
        default: 'SM-A022F-Kernel'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Building Kernel
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc gcc-arm-linux-gnueabihf binutils-arm-linux-gnueabihf make bison
        cd ${GITHUB_WORKSPACE}
        export KBUILD_BUILD_USER="${{ github.actor }}"
        export KBUILD_BUILD_HOST="${{ github.event.inputs.DEVICE_NAME }}"
        chmod +x build
        ./build
        
    - name: Set Properties
      id: props
      run: |
        echo "date=$(TZ=Asia/Jakarta date +%Y%m%d-%I%M%p)" >> $GITHUB_OUTPUT
    - name: Compressed as Archive
      run: |
        cd /home/runner/work/myKernel/out/arch/arm/boot || exit 1
        zip -r9 "${{ github.event.inputs.DEVICE_NAME }}-${{ steps.props.outputs.date }}.zip" ./* -x "dts" -x "dts/*"
    - name: Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: |
          /home/runner/work/myKernel/out/arch/arm/boot/*.zip
          /home/runner/work/myKernel/build.log
        name: Compiled Kernel for ${{ github.event.inputs.DEVICE_NAME }} - ${{ steps.props.outputs.date }}
        draft: false
        prerelease: false
        tag: ${{ github.run_id }}-${{ steps.props.outputs.date }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ## Notes
            - Extract ${{ github.event.inputs.DEVICE_NAME }}-${{ steps.props.outputs.date }}.zip, look your newly-compiled kernel inside.
            - Include building logs.
    - name: Link of Release
      run: |
        echo "Enjoy your Newly Built Kernel"
        echo "https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ github.run_id }}-${{ steps.props.outputs.date }}"
        
