name: Sapu

on:
  workflow_dispatch:

jobs:
  Cleaning:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Working now
      uses: iamazeem/delete-workflow-runs-action@v1
      with:
        include-disabled-workflows: true

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        
    - name: Add and Commit file
      run: |
        git add -A
        git commit -m "Initial"
        git push
