name: Sedot clang

on:
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Working for Clang
      run: |
        cd ${GITHUB_WORKSPACE}
        git clone https://github.com/a02-trial/toolchain -b clang11
        mkdir -p tempe
        cd toolchain && mv * ${GITHUB_WORKSPACE}/tempe/.
        cd ..
        rm -rf toolchain
        mv tempe clang
        
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        git lfs install
        git lfs track "*.1git clang-11 *.so *.11git"
        git add .gitattributes
        
    - name: Add and Commit file
      run: |
        git add *
        git commit -m "clang"
        git push
